# Generated by Django 4.1 on 2022-08-24 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=64)),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField(null=True)),
                ('gen', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.CharField(default='', max_length=250)),
                ('info', models.CharField(default='', max_length=250)),
                ('name', models.CharField(max_length=50)),
                ('rating', models.IntegerField(null=True)),
                ('collection', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gamez.collection')),
                ('platform', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gamez.platform')),
            ],
        ),
    ]
