# Generated by Django 4.0.4 on 2022-06-28 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamez', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='collection',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gamez.collection'),
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gamez.platform'),
        ),
        migrations.AddField(
            model_name='game',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='thumbnail',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='gen',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
