# Generated by Django 4.0.4 on 2022-06-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamez', '0002_collection_user_game_collection_game_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='info',
            field=models.URLField(null=True),
        ),
    ]
