# Generated by Django 4.0.4 on 2022-06-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamez', '0003_game_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='info',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='game',
            name='thumbnail',
            field=models.CharField(default='', max_length=250),
        ),
    ]
